"""vacancy field is nullable

Revision ID: 8ce3c16cb46a
Revises: b634595110c0
Create Date: 2026-06-18 14:36:08.703957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ce3c16cb46a'
down_revision: Union[str, Sequence[str], None] = 'b634595110c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancy', 'source_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('vacancy', 'employment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('vacancy', 'work_format',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('vacancy', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancy', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('vacancy', 'work_format',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('vacancy', 'employment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('vacancy', 'source_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
