"""add profile id column

Revision ID: dbdea265bda2
Revises: 8ce3c16cb46a
Create Date: 2026-06-19 13:25:29.080877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbdea265bda2'
down_revision: Union[str, Sequence[str], None] = '8ce3c16cb46a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('profile_id', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy', 'profile_id')
    # ### end Alembic commands ###
