"""Initial migration

Revision ID: b634595110c0
Revises: 
Create Date: 2026-06-16 10:29:57.372547

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b634595110c0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("source",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("name", sa.String(length=255), nullable=False),
    sa.Column("base_url", sa.String(length=500), nullable=False),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name")
    )
    op.create_table("vacancy",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("source_id", sa.Uuid(), nullable=False),
    sa.Column("external_id", sa.String(length=255), nullable=True),
    sa.Column("title", sa.String(length=255), nullable=False),
    sa.Column("description", sa.Text(), nullable=False),
    sa.Column("company_name", sa.String(length=255), nullable=True),
    sa.Column("employment_type", sa.String(length=50), nullable=False),
    sa.Column("work_format", sa.String(length=50), nullable=False),
    sa.Column("salary_min_amount", sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column("salary_max_amount", sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column("location", sa.String(length=255), nullable=True),
    sa.Column("url", sa.String(length=500), nullable=False),
    sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("status", sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(["source_id"], ["source.id"] ),
    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vacancy")
    op.drop_table("source")
    # ### end Alembic commands ###
