services:

  ccheck.frontend.web:
    container_name: ccheck-frontend-web
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: web-runtime
    env_file: ../enviroment/.frontend.env
    restart: unless-stopped
    networks:
      - ccheck_network
    ports:
      - "3000:80"
    volumes:
      - ../infra/scripts/inject-env.sh:/docker-entrypoint.d/40-inject-env.sh