services:

  user.web:
    container_name: user-web
    build:
      context: ../backend/user
      dockerfile: Dockerfile
      target: web-runtime
    env_file: ../enviroment/.user.env
    command: ["sh", "-c", "user-cli migrate && user-cli start-uvicorn"]
    restart: unless-stopped
    depends_on:
      ccheck.db:
        condition: service_healthy
      ccheck.rabbitmq:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80/healthcheck || exit 1" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ccheck_network