"""Initial migrations

Revision ID: dae91989c78e
Revises: 
Create Date: 2026-06-16 16:40:16.504197

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dae91989c78e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("search_profiles",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("user_id", sa.Uuid(), nullable=False),
    sa.Column("name", sa.String(length=255), nullable=False),
    sa.Column("keywords", sa.JSON(), nullable=False),
    sa.Column("search_interval_minutes", sa.Integer(), nullable=False),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("search_jobs",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("profile_id", sa.Uuid(), nullable=False),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("status", sa.String(length=50), nullable=False),
    sa.Column("vacancies_found", sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(["profile_id"], ["search_profiles.id"] ),
    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("search_jobs")
    op.drop_table("search_profiles")
    # ### end Alembic commands ###
