"""Initial migrations

Revision ID: 9842d19b7014
Revises: 
Create Date: 2026-06-24 11:38:15.103902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from user.domain.user.value_objects import UserRole, UserStatus
from user.infrastructure.persistence.tables.types import EnumAsString


# revision identifiers, used by Alembic.
revision: str = '9842d19b7014'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', EnumAsString(UserRole, length=20), nullable=False),
    sa.Column('status', EnumAsString(UserStatus, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
